run_mode: debug
addr: :8080
name: vc-gin-api
url: http://127.0.0.1:8080
max_ping_count: 10
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5

logger:
  writers: file,stdout
  logger_level: INFO
  logger_file: logs/vc-gin-api.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 50
  log_backup_count: 7

db:
  schema: demo
  host: 127.0.0.1
  port: 3306
  username: root
  password: root123456

redis:
  host: 127.0.0.1:6379
  index: 0
  pool_size: 10
  password: 123456
